# Generated by Django 5.0.2 on 2024-02-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('has_tests', models.BooleanField()),
                ('has_docs', models.BooleanField()),
                ('status', models.CharField(choices=[('PL', 'Planned'), ('ST', 'Started'), ('FR', 'First Results'), ('MR', 'Mature Results'), ('DO', 'Done'), ('DE', 'Deferred'), ('BL', 'Blocked'), ('IN', 'Inactive')], max_length=2)),
                ('last_review', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
